version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - symfony
    depends_on:
      - redis
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"
    networks:
      - symfony
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - symfony

networks:
  symfony:
    driver: bridge